import {
  SearchOutlined,
  UnorderedListOutlined,
  InteractionOutlined,
} from '@vicons/antd'
import { CreateOutline } from '@vicons/ionicons5'
import { renderIcon } from '@/utils/icon.js'

export default [
  {
    path: 'spec',
    meta: {
      title: '申请创建',
      icon: renderIcon(CreateOutline),
      show: true,
      role: ['admin', 'user'],
      system: 'SPEC',
    },
    children: [
      {
        path: 'create',
        name: 'SPEC申请创建',
        component: () => import('@/views/spec/form/create.vue'),
        meta: {
          title: '申请创建',
          show: true,
          role: ['admin', 'user'],
          icon: '',
          system: 'SPEC',
        },
      },
      {
        path: 'referForm',
        name: 'SPEC表单创建(有引用)',
        component: () => import('@/views/spec/form/referForm.vue'),
        meta: {
          title: 'SPEC表单创建(有引用)',
          show: false,
          role: ['admin', 'user'],
          icon: '',
          system: 'SPEC',
          activeMenu: '/pages/spec/create',
        },
      },
      {
        path: 'form',
        name: 'SPEC表单创建(无引用)',
        component: () => import('@/views/spec/form/index.vue'),
        meta: {
          title: '表单创建(无引用)',
          show: false,
          role: ['admin', 'user'],
          icon: '',
          system: 'SPEC',
          activeMenu: '/pages/spec/create',
        },
      },
      {
        path: 'cancelForm',
        name: 'SPEC表单作废',
        component: () => import('@/views/spec/form/cancelForm.vue'),
        meta: {
          title: '表单作废',
          show: false,
          role: ['admin', 'user'],
          icon: '',
          system: 'SPEC',
          activeMenu: '/pages/spec/create',
        },
      },
      {
        path: 'editForm',
        name: 'SPEC表单修订',
        component: () => import('@/views/spec/form/editForm.vue'),
        meta: {
          title: '表单修订',
          show: false,
          role: ['admin', 'user'],
          icon: '',
          system: 'SPEC',
          activeMenu: '/pages/spec/create',
        },
      },
      {
        path: 'uploadInfo',
        name: 'SPEC导入规格书',
        component: () => import('@/views/spec/component/UploadInfo.vue'),
        meta: {
          title: '导入规格书',
          show: false,
          role: ['admin', 'user'],
          icon: '',
          system: 'SPEC',
          activeMenu: '/pages/spec/create',
        },
      },
      {
        path: 'importForm',
        name: 'SPEC表单导入',
        component: () => import('@/views/spec/form/importForm.vue'),
        meta: {
          title: '表单导入',
          show: false,
          role: ['admin', 'user'],
          icon: '',
          system: 'SPEC',
          activeMenu: '/pages/spec/create',
        },
      },
      {
        path: 'todo',
        name: 'SPEC审批列表',
        component: () => import('@/views/approval/todo.vue'),
        meta: {
          title: '审批列表',
          show: true,
          role: ['admin', 'user'],
          icon: '',
          system: 'SPEC',
        },
      },
      {
        path: 'draft',
        name: 'SPEC草稿箱',
        component: () => import('@/views/approval/draft.vue'),
        meta: {
          title: '草稿箱',
          show: true,
          role: ['admin', 'user'],
          icon: '',
          system: 'SPEC',
        },
      },
      {
        path: 'done',
        name: 'SPEC我的已办',
        component: () => import('@/views/approval/done.vue'),
        meta: {
          title: '我的已办',
          show: true,
          role: ['admin', 'user'],
          icon: '',
          system: 'SPEC',
        },
      },
      {
        path: 'apply',
        name: 'SPEC我的申请',
        component: () => import('@/views/approval/apply.vue'),
        meta: {
          title: '我的申请',
          show: true,
          role: ['admin', 'user'],
          icon: '',
          system: 'SPEC',
        },
      },
    ],
  },
  {
    path: 'spec/find',
    name: 'SPEC查找中心',
    component: () => import('@/views/spec/find/index.vue'),
    meta: {
      title: '查找中心',
      icon: renderIcon(SearchOutlined),
      show: true,
      role: ['admin', 'user'],
      system: 'SPEC',
    },
  },
  {
    path: 'spec/editRoute',
    name: 'SPEC申请单编辑路由',
    component: () => import('@/views/approval/editRoute.vue'),
    meta: {
      title: '申请单编辑路由',
      icon: renderIcon(InteractionOutlined),
      show: true,
      role: ['admin'],
      system: 'SPEC',
    },
  },
  {
    path: 'spec/actionLog',
    name: 'SPEC编辑路由操作日志',
    component: () => import('@/views/approval/actionLog.vue'),
    meta: {
      title: '编辑路由操作日志',
      icon: renderIcon(UnorderedListOutlined),
      show: true,
      role: ['admin'],
      system: 'SPEC',
    },
  },
]
